# Generated by Django 4.2 on 2023-06-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="snippet", old_name="code", new_name="data",),
        migrations.RemoveField(model_name="snippet", name="language",),
        migrations.RemoveField(model_name="snippet", name="linenos",),
        migrations.RemoveField(model_name="snippet", name="style",),
    ]
