# Generated by Django 4.2 on 2023-07-01 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_crcinfo_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crcinfo',
            options={},
        ),
    ]
